config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'

  resources :task_members
  resources :team_members
  resources :team_projects
  resources :teams
  resources :projects
  devise_for :users
  resources :tasks do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @projects = user_projects
    @tasks    = current_user.tasks.all
  end

  private
    def user_projects
      # Get all projects associated with the user.
      project_list = current_user.projects

      # Add all projects connected to the teams a user is in.
      current_user.teams.each do |team|
        project_list += team.projects
      end

      # Remove duplicates
      project_list.uniq
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def welcome_message
    message = "Welcome "
    message += "back " if current_user.sign_in_count > 1
    message += current_user.email
  end

  def calculate_task_tree(project:)
    hierarchy = project.tasks.map(&:hierarchy)

    markup = ""
    hierarchy.each do |level|
      markup += handle_level(level)
    end
    markup
  end

  def handle_level(level)
    markup = ""

    keys = level.keys
    keys.each do |key|
      markup += "<li><span class='caret caret-text'>#{ key.try(:name) }</span>"
      markup += "<ul class='nested'>"

      row = level[key]
      markup += handle_children(row)

      markup += "</ul>"
      markup += "</li>"
    end

    markup
  end

  def handle_children(row)
    markup = ""
    
    if keys? row # this is a hash
      markup += handle_level(row)
    else # this is an array
      row.each do |val|
        markup += keys?(val) ? handle_level(val) : "<li>#{val.name}</li>"
      end
    end

    markup
  end

  private
  def keys?(val)
    val.is_a? Hash
  end
end

app/views/static_pages/_recent_activity.html.erb
<p>Bacon ipsum dolor amet landjaeger jerky drumstick doner, chuck biltong meatloaf. Hamburger doner short loin </br>
1 day ago</p>
<p>Beef ribs ball tip brisket doner kevin jerky pork burgdoggen </br>
1 day ago</p>
<p>Pig beef bacon, tri-tip pork meatloaf swine pancetta prosciutto venison jowl picanha </br>
2 day ago</p>
<p>Tri-tip capicola drumstick bresaola. Strip steak rump swine sirloin capicola ham salami beef ribs, tongue corned beef kevin t-bone. </br>
1 week ago</p>

app/views/static_pages/_tasks_cards.html.erb
<div class="row no-gutters">
  <% if @tasks.present? %>
    <h3 class="home-page-heading">
      Tasks
      <span class="badge badge-info counter"><p><%= @tasks.size %></p></span>
    </h3>

<!--     <% projects.each do |project| %>
      <div class="home-page-heading">
        <ul class="task-tree">
          <%= raw calculate_task_tree(project: project) %>
        </ul>
      </div>
    <% end %> -->
    <% @tasks.each do |task| %>
      <div class='col-lg-3 col-md-4 col-sm-12'>
        <a class='card' href=<%= task_path(task) %>>
          <div class="card-body">
          <h4 class="card-title"><%= task.name %></h4>
          <% if task.description.present? %>
            <p class="card-text"><%= task.description %></p>
          <% end %>
        </div>
        </a>
      </div>
    <% end %>
  <% end %>
</div>
<%= javascript_include_tag 'static_pages', 'data-turbolinks-track' => true %>

app/views/static_pages/_teams_cards.html.erb
<div class="row no-gutters">
  <h3 class="home-page-heading">
    <%= link_to "Teams", teams_url %>
    <span class="badge badge-info counter"><p><%= current_user.teams.try(:size) %></p></span>
    <a class='btn btn-default pull-right' href=<%= new_team_path %>>
      <span class="glyphicon glyphicon-plus" />
    </a>
  </h3>
  <% if current_user.teams.empty? %>
    <p>You are not working on any projects at the moment</p>
  <% end %>
  <% current_user.teams.each do |team| %>
    <div class='col-lg-3 col-md-4 col-sm-12'>
      <a class='card' href=<%= team_path(team) %>>
        <div class="card-body">
        <h4 class="card-title"><%= team.name %></h4>
        <% if team.description.present? %>
          <p class="card-text"><%= team.description %></p>
        <% end %>
        <p class="card-text">Role: <%= capitalize_name get_user_role current_user, team %></p>
      </div>
      </a>
    </div>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:active_nav, 'home') %>
<div class="page-header">
  <h3><%= welcome_message %></h3>
  <h1>Your Dashboard</h1>
</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <%= render partial: "projects/project_list" %>
    <%= render partial: "teams/team_list" %>
    <%= render partial: "tasks_cards", locals: {projects: @projects} %>
  </div>
</div>