config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'

  resources :task_members
  resources :team_members
  resources :team_projects
  resources :teams
  resources :projects
  devise_for :users
  resources :tasks do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :user
  belongs_to :team

  validates_uniqueness_of :user_id, scope: :team
  validates :role, presence: true

  enum role: [:can_work_on_tasks, :can_manage_tasks, :can_manage_team, :admin]

  before_destroy :destroy_team?

  def is_last_team_admin?
    num_of_admins = team.team_members.where(role: TeamMember.roles[:admin]).count

    # returns true if there is only 1 admin in the team and this member is an admin.
    num_of_admins == 1 && TeamMember.roles[role] == TeamMember.roles[:admin]
  end

  private
    def destroy_team?
      team.destroy if is_last_team_admin?
    end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :update, :edit, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
    @team = Team.find(params[:team_id]) if params[:team_id].present?

    respond_to do |format|
      if ! available_members?
        format.js { render template: 'shared/error', locals: {
          title: 'Cannot add a member',
          message: 'There are no users available to be added to a team'
        }}
        flash.now[:alert] = 'There are no users available to be added to a team'
      end

      format.html
      format.js { render template: 'shared/modal_form', locals: {
        title: 'Add a Team Member',
        form: 'team_members/form'
      }}
    end
  end

  # GET /team_members/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js { render template: 'shared/modal_form', locals: {
        title: 'Edit Member',
        form: 'team_members/form'
      }}
    end
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        flash[:notice] = 'Team member was successfully created.';
        format.html { redirect_to team_path(@team_member.team_id) }
        format.json { render :show, status: :created, location: @team_member }
        format.js  { render template: 'shared/reload' }
      else
        format.html { render :new}
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        flash[:notice] = 'Team member was successfully updated.';
        format.html { redirect_to team_path(@team_member.team_id) }
        format.json { render :show, status: :ok, location: @team_member }
        format.js  { render template: 'shared/reload' }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy

    respond_to do |format|
      format.html { redirect_to target_url, notice: 'Team member was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:user_id, :team_id, :role)
    end

    # If the member being removed is the current_user then they have removed themselves from the team.
    def target_url
      @team_member.user_id == current_user.id ? root_url : team_path(@team_member.team.id)
    end

    def available_members?
      @team.present? && @team.team_members.count != User.all.count
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
  def users_for_selection
    User.all - team_users
  end

  def team_users
    @team.present? ? @team.users : []
  end

  def roles_for_select
    TeamMember.roles.map{|k, v| [capitalize_name(k), k] }
  end
end

app/views/team_members/_form.html.erb
<%= form_for(@team_member, remote: true, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @team_member.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@team_member.errors.count, "error") %> prohibited this team_member from being saved:</h4>

      <ul>
      <% @team_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @team_member.user_id.present? %>
    <div class="form-group">
      <%= f.label :user_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :user_id, (users_for_selection).collect{|p| [p.username, p.id]}, { include_blank: false}, :disabled => "disabled", class: "form-control" %>
      </div>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :user_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :user_id, (users_for_selection).collect{|p| [p.username, p.id]}, { include_blank: false }, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :team_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.hidden_field :team_id, :value => params[:team_id], class: "form-control" %>
    </div>
  </div>

  <% if @team_member.user_id.present? %>
    <% if @team_member.is_last_team_admin? %>
    <div class="form-group">
      <%= f.label :role, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :role, roles_for_select, { include_blank: false }, :disabled => "disabled", class: "form-control" %>
      </div>
    </div>
    <% else %>
    <div class="form-group">
      <%= f.label :role, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :role, roles_for_select, { include_blank: false }, class: "form-control" %>
      </div>
    </div>
    <% end %>
  <% else %>
  <div class="form-group">
    <%= f.label :role, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :role, roles_for_select, { include_blank: false }, class: "form-control" %>
    </div>
  </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary pull-right" %>
    </div>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<div class="page-header">
  <%= link_to team_path(@team_member.team_id), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @team_member, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <% if @team_member.is_last_team_admin? %>
    <%= link_to team_member_path(@team_member), data: {confirm: "#{@team_member.user.username} is the last team admin.\nRemoving this team member will delete the team!" }, :method => :delete, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-minus"></span>
      Remove Team Member
    <% end %>
  <% else %>
    <%= link_to team_member_path(@team_member), data: {confirm: "Are you sure you want to remove #{@team_member.user.username} from the team?" }, :method => :delete, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-minus"></span>
      Remove Team Member
    <% end %>
  <% end %>
  <h1>Manage Team Member</h1>
</div>

<%= render 'form'%>

app/views/team_members/index.html.erb
<div class="page-header">
  <%= link_to new_team_member_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Team member
  <% end %>
  <h1>Listing Allocated Team Members</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th>Team</th>
            <th>Role</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @team_members) do |team_member| %>
            <td><%= team_member.user.try(:username) || "None" %></td>
            <td><%= link_to( team_member.team.name, teams_path(team_member.team) ) %></td>
            <td><%= capitalize_name team_member.role %></td>
            <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/team_members/new.html.erb
<div class="page-header">
  <%= link_to team_members_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Team Member</h1>
</div>

<%= render 'form' %>

app/views/team_members/show.html.erb
<div class="page-header">
  <%= link_to team_path(@team_member.team_id), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_team_member_path(@team_member), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Team Members</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @team_member.user.username || "None" %></dd>

  <dt>Team:</dt>
  <dd><%= link_to( @team_member.team.name, teams_path(@team_member.team) ) %></dd>

  <dt>Role:</dt>
  <dd><%= capitalize_name @team_member.role %></dd>

</dl>