config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'

  resources :task_members
  resources :team_members
  resources :team_projects
  resources :teams
  resources :projects
  devise_for :users
  resources :tasks do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
end

app/models/task_member.rb
class TaskMember < ApplicationRecord
  # include Tombstoneable

  belongs_to :user
  belongs_to :task

  validates_uniqueness_of :user_id, scope: :task
  validate :user_can_join_task

  # Will return true if the user is in a team connected to a project.
  def user_can_join_task
    unless task.parent_project.has_participant? user
      errors.add(:user, "must be in a team attached to the project this task is a part of.")
    end
  end
end

app/controllers/task_members_controller.rb
class TaskMembersController < ApplicationController
  before_action :set_task_member, only: [:destroy]

  # GET /task_members/new
  def new
    @task_member = TaskMember.new
    @task = Task.find_by(id: params[:task]);

    # If user is not nil then the user is trying to add themselves.
    @user = User.find_by(id: params[:user]) if params[:user].present?
    @candidate_members = @task.parent_project.users - @task.users

    respond_to do |format|
      format.html
      format.js { render template: 'shared/modal_form', locals: {
        title: 'Add Member to Task',
        form: 'task_members/form'
      }}
    end
  end

  # POST /task_members
  # POST /task_members.json
  def create
    # Check if the task member has been removed at some point.
    # @task_member = TaskMember.deleted.find_by(task_id: task_member_params[:task_id], user_id: task_member_params[:user_id])

    # if @task_member.present?
    #   undelete
    # else
      create_new
    # end
  end

  # DELETE /task_members/1
  # DELETE /task_members/1.json
  def destroy
    @task_member.destroy

    respond_to do |format|
      flash[:notice] = 'Task member was successfully destroyed.'
      format.js
      format.html { redirect_to task_members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_member
      @task_member = TaskMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_member_params
      params.require(:task_member).permit(:task_id, :user_id)
    end

    # Object does not exist in the database. Create a new object.
    def create_new
      @task_member = TaskMember.new(task_member_params)

      respond_to do |format|
        if @task_member.save
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @task_member.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end

    # Object already exists. Set the delete flag to false.
    def undelete
      respond_to do |format|
        if @task_member.undelete!
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @task_member.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/task_members_helper.rb
module TaskMembersHelper
  def show_delete_action_for(member:, user:) 
    user.can_manage?(task: member.task) || member.user == user
  end
end

app/views/task_members/_add_button.html.erb
<%= link_to new_task_member_path(parameters), {
  :remote => true,
  class: 'btn btn-default pull-right',
  style: ('display: none;' if hidden).to_s,
  data: {
    toggle: 'modal',
    target: '#modal-window'
  }
} do %>
  <span class="glyphicon glyphicon-plus" />
<% end %>

app/views/task_members/_create.html.erb
<%= render partial: 'member', locals: { task_member: @task_member } %>

app/views/task_members/_form.html.erb
<% if ! @candidate_members.empty? %>
  <%= form_for(@task_member, remote: true, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if @task_member.errors.any? %>
      <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4><%= pluralize(@task_member.errors.count, "error") %> prohibited this task_member from being saved:</h4>

        <ul>
        <% @task_member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= hidden_field :task_member, :task_id, value: @task.id, class: "form-control" %>
    </div>
    <% if @user.nil? %>
      <div class="form-group">
        <%= f.label :user, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.select :user_id, @candidate_members.collect {|user| [user.username, user.id]} %>
        </div>
      </div>
    <% else %>
      <p>Do you want to add yourself to the task?</p>
      <%= hidden_field :task_member, :user_id, value: @user.id, class: "form-control" %>
    <% end %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10 pull-right">
        <%= f.submit value: "Add", class: "btn btn-primary pull-right" %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>There are no available users to join this task</p>
  <div style="text-align: right;">
    <button type="button" class="btn btn-primary" data-dismiss="modal">
      Close
    </button>
  </div>
<% end %>

app/views/task_members/_member.html.erb
<%= content_tag(:li, 
    id: 'task-member-' + task_member.id.to_s,
    class: 'task-member') do %>
  <div class="icon-container">
    <%= content_tag(:div, class: 'user-icon',
      data: {
        toggle: 'popover',
        html: true,
        placement: 'bottom',
        template: (render(partial: 'task_members/popover', locals: {task_member: task_member})),
        title: task_member.user.username,
        content: task_member.user.email
      }) do %>
        <h3><%= task_member.user.username[0..1].capitalize %></h3>
      <% end %>
  </a>
<% end %>

app/views/task_members/_popover.html.erb
<div class="popover" role="popover">
  <div class="arrow"></div>
  <div class="popover-inner">
    <div class="popover-header">
      <h3 class="popover-title"></h3>
      <% if show_delete_action_for(member: task_member, user: current_user) %>
        <%= link_to task_member_path(task_member), remote: true, method: :delete, title: 'Remove user from task?', data: { 
          confirm: 'Remove user from task?', toggle: 'tooltip', placement: 'top' 
        } do %>
          <span class="glyphicon glyphicon-trash" />
        <% end %>
      <% end %>
    </div>
    <div class="popover-content"></div>
  </div>
</div>

app/views/task_members/_task_members.html.erb
<div id="task-members">
  <h3 class="home-page-heading">
    Task Members
    <span class="badge badge-info counter"><p><%= @task.task_members.size %></p></span>
    <% if @can_manage_task %>
      <%= render partial: 'task_members/add_button', locals: {parameters: {task: @task}, hidden: false} %>
    <% elsif ! @task.has_participant? current_user # allow the user to add themselves %>
      <%= render partial: 'task_members/add_button', locals: {parameters: {task: @task, user: current_user}, hidden: false} %>
    <% else # User is already a member, hide the button. Shown if the user removes themselves %>
      <%= render partial: 'task_members/add_button', locals: {parameters: {task: @task, user: current_user}, hidden: true} %>
    <% end %>
  </h3>

  <ul class="row no-gutters">
    <% if @task.task_members.size > 0 %>
        <% @task.task_members.each do |member| %>
          <%= render partial: 'task_members/member', locals: { task_member: member } %>
        <%end %>
    <% else %>
      <p id="no-task-members">There are no users currently associated with this task.</p>
    <%end %>
  </ul>
</div>

app/views/task_members/create.js.erb
// Close the modal.
$('#modal-window').modal('toggle');

// Remove the no users message if present.
$('#no-task-members').remove();

// Add the member to the member icons.
$('#task-members ul').append("<%= j render 'create' %>");

// Add event handlers
addPopoverEvent($('.user-icon').last());
addTooltipEvent($('.user-icon').last());

// Increment the counter.
$('#task-members .counter p').text(parseInt($('#task-members .counter p').text()) + 1);

// Check if the add button should be hidden.
var userIsManager = '<%= current_user.can_manage?(task: @task_member.task) %>';
var memberIsCurrentUser = '<%= @task_member.user == current_user %>';

if(userIsManager == 'false' && memberIsCurrentUser == 'true' ) {
  $('#task-members .btn').fadeOut();
}

app/views/task_members/destroy.js.erb
// Remove the element.
$('#task-member-<%= @task_member.id %>').fadeOut(function() {
  $(this).remove();
  // Add no users message if there are no more members.
  if ($('.task-member').length == 0 ) {
    $('#task-members').append($('<p id="no-task-members">There are no users currently associated with this task.</p>'));
  }
});

// Decrement the counter.
$('#task-members .counter p').text(parseInt($('#task-members .counter p').text()) - 1);

// Check if the add button should be shown.
var userIsManager = '<%= current_user.can_manage?(task: @task_member.task) %>';
var memberIsCurrentUser = '<%= @task_member.user == current_user %>';

if(userIsManager == 'false' && memberIsCurrentUser == 'true' ) {
  $('#task-members .btn').fadeIn();
}

app/views/task_members/edit.html.erb
<div class="page-header">
  <%= link_to task_members_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task_member, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing task_member</h1>
</div>

<%= render 'form' %>

app/views/task_members/index.html.erb
<div class="page-header">
  <%= link_to new_task_member_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Task member
  <% end %>
  <h1>Listing task_members</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Task</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @task_members) do |task_member| %>
            <td><%= task_member.task %></td>
            <td><%= task_member.user %></td>
            <td><%= link_to 'Show', task_member %></td>
        <td><%= link_to 'Edit', edit_task_member_path(task_member) %></td>
        <td><%= link_to 'Destroy', task_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/task_members/new.html.erb
<div class="page-header">
  <%= link_to task_members_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New task_member</h1>
</div>

<%= render 'form' %>

app/views/task_members/show.html.erb
<div class="page-header">
  <%= link_to task_members_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_task_member_path(@task_member), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show task_member</h1>
</div>

<dl class="dl-horizontal">
  <dt>Task:</dt>
  <dd><%= @task_member.task %></dd>

  <dt>User:</dt>
  <dd><%= @task_member.user %></dd>

</dl>