config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'

  resources :task_members
  resources :team_members
  resources :team_projects
  resources :teams
  resources :projects
  devise_for :users
  resources :tasks do
    resources :comments
  end

  resources :comments do
    resources :replies
  end
end

app/models/project.rb
class Project < ApplicationRecord
  # include Tombstoneable

  has_many  :project_owners
  has_many  :users, as: :owners, through: :project_owners, dependent: :destroy

  has_many   :tasks, as: :parent, dependent: :destroy

  has_many   :team_projects
  has_many   :teams, through: :team_projects, dependent: :destroy

  accepts_nested_attributes_for :project_owners, allow_destroy: true

  validates  :name, presence: true, length: { maximum: 256 }

  # Check if a user is in a team connected to the project.
  def has_participant? user
    teams.any?{|team| team.has_participant? user }
  end

  def users
    users = []

    teams.each do |team|
      users += team.users
    end

    users.uniq
  end

  def can_add_task? user
    teams.each do |team|
      team.team_members.each do |member|
        return true if member.user == user && TeamMember.roles[member.role] >= TeamMember.roles[:can_manage_tasks]
      end
    end

    return false
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  breadcrumb 'Projects', :projects_path, match: :exact

  # GET /projects
  # GET /projects.json
  def index
    @projects = user_projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = @project.tasks
    breadcrumb @project.name, project_path(@project.id), match: :exact
  end

  # GET /projects/new
  def new
    @project = Project.new

    respond_to do |format|
      format.html
      format.js { render template: 'shared/modal_form', locals: {
        title: 'Create New Project',
        form: 'projects/form'
      }}
    end
  end

  # GET /projects/1/edit
  def edit
    @team_projects = @project.team_projects.empty? ? [TeamProject.new] : @project.team_projects

    respond_to do |format|
      format.html
      format.js { render template: 'shared/modal_form', locals: {
        title: 'Edit Project',
        form: 'projects/form'
      }}
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to @project }
        format.json { render :show, status: :created, location: @project }
        format.js { render template: 'shared/redirect', locals: {path: project_path(@project) } }
      else
        format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
        flash.now[:alert] = 'A problem was encountered creating the project!'
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to @project }
        format.json { render :show, status: :ok, location: @project }
        format.js  { render template: 'shared/reload' }
      else
        format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
        flash.now[:alert] = 'A problem was encountered updating the project!'
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project].merge!({ project_owners_attributes: [user_id: current_user.id] })
      params.require(:project).permit(
        :name,
        :description,
        project_owners_attributes: [:user_id]
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user, value: current_user.id, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary pull-right", remote: true %>
    </div>
  </div>
<% end %>

app/views/projects/_project_list.html.erb
<div class="row no-gutters">
  <h3 class="home-page-heading">
    Projects
    <span class="badge badge-info counter"><p><%= @projects.size %></p></span>
    <%= link_to new_project_path, remote: true, class: 'btn btn-default pull-right' do %>
      <span class="glyphicon glyphicon-plus" />
    <% end %>
  </h3>
  <% if @projects.empty? %>
    <p>You are not working on any projects at the moment</p>
  <% end %>
  <% @projects.each do |project| %>
    <%= render partial: 'layouts/card', locals: {
      target_link: project_path(project),
      card_type: 'project',
      title: project.name,
      description: (project.description if project.description.present?)
    } %>
  <% end %>
</div>

app/views/projects/_tasks.html.erb
<% @tasks.each do |task| %>
  <div class='col-lg-3 col-md-4 col-sm-12'>
    <div class='card'>
      <a class="card-body"  href=<%= task_path(task) %>>
        <h4 class="card-title"><%= task.name %></h4>
        <% if task.description.present? %>
          <p class="card-text"><%= task.description %></p>
        <% end %>
      </a>

      <% if user_can_manage_task?(user: current_user, task: task) %>
        <div class="card-footer">
          <div class="slide-menu">
            <div class="menu-container">
              <div class="menu-toggle">
                <span class="glyphicon glyphicon-menu-hamburger"></span>
                <span class="glyphicon glyphicon-remove"></span>
              </div>
              <div class="menu-items">
                <%= link_to task, method: :delete,
                  data: { confirm: "Are you sure you want to remove this task from the project?" } do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/_teams.html.erb
<% if @project.teams.empty? %>
  <p>No teams have been assigned to this project yet</p>
<% end %>
<% @project.teams.each do |team| %>
  <div class='col-lg-3 col-md-4 col-sm-12'>
    <% if user_is_team_member?(team) %>
      <div class='card'>
        <a class="card-body"  href=<%= team_path(team) %>>
          <h4 class="card-title"><%= team.name %></h4>
          <% if team.description.present? %>
            <p class="card-text"><%= team.description %></p>
          <% end %>
        </a>

        <% if user_is_project_owner? @project %>
          <div class="card-footer">
            <div class="slide-menu">
              <div class="menu-container">
                <div class="menu-toggle">
                  <span class="glyphicon glyphicon-menu-hamburger"></span>
                  <span class="glyphicon glyphicon-remove"></span>
                </div>
                <div class="menu-items">
                  <%= link_to @project.team_projects.find_by(team_id: team.id), method: :delete,
                    data: { confirm: "Are you sure you want to remove this team from the project?" } do %>
                    <span class="glyphicon glyphicon-trash"></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    <% else %>
      <div class='card'>
        <div class="card-body">
          <h4 class="card-title"><%= team.name %></h4>
          <% if team.description.present? %>
            <p class="card-text"><%= team.description %></p>
          <% end %>
          <p class="card-footer">Placeholder: Not a member</p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, 'Editing Project - ' + @project.name) %>
<% provide(:active_nav, 'projects') %>
<div class="page-header">
  <%= link_to request.referer, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-circle-arrow-left"></span>
    Back
  <% end %>
  <%= link_to @project, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<% provide(:title, 'Showing Projects') %>
<% provide(:active_nav, 'projects') %>
<div class="page-header">
  <h1>Listing projects for: <%= current_user.username %></h1>
</div>

<%= render 'projects/project_list' %>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<% provide(:active_nav, 'projects') %>
<div class="page-header">
  <%= link_to request.referer, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-circle-arrow-left"></span>
    Back
  <% end %>
  <h1>New project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<% provide(:title, 'Project - ' + @project.name) %>
<% provide(:active_nav, 'projects') %>
<div class="page-header">
  <h1><%= @project.name %>
    <% if user_is_project_owner? @project %>
      <div class="slide-menu">
        <div class="menu-container">
          <div class="menu-toggle">
            <span class="glyphicon glyphicon-menu-hamburger"></span>
            <span class="glyphicon glyphicon-remove"></span>
          </div>
          <div class="menu-items">
            <%= link_to edit_project_path, remote: true do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <%= link_to @project, method: :delete,
              data: { confirm: "Are you sure you want to delete this project?" } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </h1>
</div>

<% if @project.description.present? %>
  <dl class="dl-horizontal">
    <dt>Description:</dt>
    <dd><%= @project.description %></dd>
  </dl>
<% end %>

<div class="row no-gutters">
  <h3 class="home-page-heading">Tasks
    <span class="badge badge-info counter"><p><%= @project.tasks.size %></p></span>
    <% if @project.can_add_task? current_user %>
      <%= link_to new_task_path(parent_type: @project.class.name, parent_id: @project), remote: true, class: 'btn btn-primary pull-right' do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    <% end %>
  </h3>
  <!-- <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Status</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tasks) do |task| %>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= capitalize_name(task.status) %></td>
            <td><%= link_to 'Show', task_path(task) %></td>
        <td><%= link_to 'Edit', edit_task_path(task), remote: true %></td>
        <td><%= link_to 'Destroy', task_path(task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table> -->
  <%= render 'tasks' %>
</div>

<div class="row no-gutters">
  <h3 class="home-page-heading">Teams
    <span class="badge badge-info counter"><p><%= @project.teams.size %></p></span>
    <% if user_is_project_owner? @project %>
      <%= link_to new_team_project_path(project: @project), remote: true, class: 'btn btn-default pull-right' do %>
        <span class="glyphicon glyphicon-plus" />
      <% end %>
    <% end %>
  </h3>
  <%= render "teams" %>
</div>